// Firestore collection names, centralized so schema changes happen in one place.
export const COLLECTIONS = {
  USERS: 'users',
  USERNAMES: 'usernames',
  CUSTOMER_MASTER: 'customerMaster',
  CREDIT_ACCOUNTS: 'creditAccounts',
  INVOICES: 'invoices',
  PAYMENTS: 'payments',
  PAYMENT_ALLOCATIONS: 'paymentAllocations',
  RECEIPTS: 'receipts',
  RECEIPT_ALLOCATIONS: 'receiptAllocations',
  JOURNAL_LEDGER: 'journalLedger',
  ADJUSTMENTS: 'adjustments',
  DEPARTMENTS: 'departments',
  REFERENCE_PERSONS: 'referencePersons',
  AUDIT_LOGS: 'auditLogs',
  NOTIFICATIONS: 'notifications',
  SETTINGS: 'settings',
  COUNTERS: 'counters',
};
