export const ROLES = {
  ADMIN: 'Administrator',
  CREDIT_OFFICER: 'Credit Control Officer',
  ACCOUNTS: 'Accounts Department',
  MANAGEMENT: 'Management',
};

export const ALL_ROLES = Object.values(ROLES);

// Central permission matrix. Keys are permission slugs used across the app.
export const PERMISSIONS = {
  MANAGE_USERS: [ROLES.ADMIN],
  MANAGE_PERMISSIONS: [ROLES.ADMIN],
  BACKUP_DATABASE: [ROLES.ADMIN],
  VIEW_AUDIT_LOGS: [ROLES.ADMIN],
  MANAGE_CUSTOMERS: [ROLES.ADMIN, ROLES.CREDIT_OFFICER],
  MANAGE_DEPARTMENTS: [ROLES.ADMIN],
  MANAGE_REFERENCE_PERSONS: [ROLES.ADMIN, ROLES.CREDIT_OFFICER],
  MANAGE_CREDIT_LIMITS: [ROLES.ADMIN],
  IMPORT_FO_REPORT: [ROLES.ADMIN, ROLES.CREDIT_OFFICER],
  CREATE_INVOICES: [ROLES.ADMIN, ROLES.CREDIT_OFFICER],
  MANAGE_INVOICE_CATEGORY: [ROLES.ADMIN, ROLES.CREDIT_OFFICER, ROLES.ACCOUNTS],
  RECORD_PAYMENTS: [ROLES.ADMIN, ROLES.CREDIT_OFFICER],
  ALLOCATE_PAYMENTS: [ROLES.ADMIN, ROLES.CREDIT_OFFICER],
  GENERATE_RECEIPTS: [ROLES.ADMIN, ROLES.CREDIT_OFFICER],
  SEND_REMINDERS: [ROLES.ADMIN, ROLES.CREDIT_OFFICER],
  VERIFY_PAYMENTS: [ROLES.ADMIN, ROLES.ACCOUNTS],
  MODIFY_REFERENCES: [ROLES.ADMIN, ROLES.ACCOUNTS],
  APPROVE_ADJUSTMENTS: [ROLES.ADMIN, ROLES.ACCOUNTS],
  DELETE_FINANCIAL_RECORDS: [ROLES.ADMIN],
  EXPORT_REPORTS: [ROLES.ADMIN, ROLES.CREDIT_OFFICER, ROLES.ACCOUNTS, ROLES.MANAGEMENT],
  VIEW_REPORTS: [ROLES.ADMIN, ROLES.CREDIT_OFFICER, ROLES.ACCOUNTS, ROLES.MANAGEMENT],
  MANAGE_SETTINGS: [ROLES.ADMIN],
};

export function hasPermission(role, permission) {
  const allowed = PERMISSIONS[permission];
  if (!allowed) return false;
  return allowed.includes(role);
}
